test_get_number_of_char (__main__.TestExercice) ... ERROR
test_get_number_of_words (__main__.TestExercice) ... FAIL
test_pair (__main__.TestExercice) ... ok
test_remove_third_char (__main__.TestExercice) ... ok
test_replace_char (__main__.TestExercice) ... ok

======================================================================
ERROR: test_get_number_of_char (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 59, in test_get_number_of_char
    output = [exercice.get_number_of_char(v[0], v[1]) for v in values]
  File "test_exercice.py", line 59, in <listcomp>
    output = [exercice.get_number_of_char(v[0], v[1]) for v in values]
  File "/home/runner/work/2021h-ch4-exercices-Juliette-Mathivet/2021h-ch4-exercices-Juliette-Mathivet/exercice.py", line 27, in get_number_of_char
    if string[i] == char:
NameError: name 'i' is not defined

======================================================================
FAIL: test_get_number_of_words (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 81, in test_get_number_of_words
    "Mauvais calcul du nombre d'occurence du mot"
AssertionError: Lists differ: [1, 0, 1] != [2, 0, 1]

First differing element 0:
1
2

- [1, 0, 1]
?  ^

+ [2, 0, 1]
?  ^
 : Mauvais calcul du nombre d'occurence du mot

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1, errors=1)
